services:
    client:
        container_name: react
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - server
        networks:
            - market_place
    server:
        container_name: node
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3333:3333"
        networks:
            - market_place
        depends_on:
            - mysql
    mysql:
        container_name: mysql
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3307:3306"
        networks:
            - market_place
        volumes:
            - mysql_data:/var/lib/mysql
networks:
    market_place:
        driver: bridge
volumes:
    mysql_data:
        driver: local
