services:
    client:
        container_name: react
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        depends_on:
            - server
        networks:
            - market_place
    server:
        container_name: node
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3333:3333"
        networks:
            - market_place
        depends_on:
            - mysql
    mysql:
        container_name: mysql
        image: mysql
        env_file:
            - ./server/.env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        expose:
            - "3306"
        networks:
            - market_place
        volumes:
            - mysql_data:/var/lib/mysql
    redis:
        container_name: redis
        image: redis:7.2.5-alpine
        expose:
            - "6379"
        networks:
            - market_place
        command: redis-server --appendonly yes
networks:
    market_place:
        driver: bridge
volumes:
    mysql_data:
        driver: local
